### ISSUE TITLE
Highlight Matching color is too similar to line highlight

### ISSUE THREAD

**Issue by Niichie** [whizkydee/vscode-material-palenight-theme#1]
Basically, you cant see matching tags. See screenshot below:
![capture](https://user-images.githubusercontent.com/16381287/28358335-85d1c43e-6c3c-11e7-82d4-980570149208.JPG)

compared to say, dracula-soft
![2](https://user-images.githubusercontent.com/16381287/28358346-8f39e40c-6c3c-11e7-8bb0-ff2643c9e0bc.JPG)

**Comment by whizkydee** [comment]
Hey @Niichie ,

Thanks for reporting 👍 . I'm sorry, but I can't understand exactly what you're saying. If you could give a little more detail about the issue, that'd be great.

**Comment by Niichie** [comment]
The color that you have set for the bracket matching (when the opening and closing tag are highlighted) is almost invisible with this theme.
This theme:
![28358335-85d1c43e-6c3c-11e7-82d4-980570149208](https://user-images.githubusercontent.com/16381287/28429749-d185ca64-6d4b-11e7-90a7-bb8f1cd18111.JPG)

Dracula:
![28358346-8f39e40c-6c3c-11e7-8bb0-ff2643c9e0bc](https://user-images.githubusercontent.com/16381287/28429753-d38d2d3e-6d4b-11e7-98b2-367699c0da19.JPG)

As you see, in dracula the highlight for the 2 `div` tags is very visible. In your theme the 2 highlights are basically invisible because the color matches the background too much.

**Comment by whizkydee** [comment]
Thanks @Niichie ,

I'll consider that in the next release `v1.0.11`.

**Comment by mustafawm** [comment]
Hi @whizkydee, thanks for the awesome theme! 

I was about to make the same suggestion but came across this one. 

Can you pls make the selection highlight a bit different (maybe darker or less transparent). 

![screen shot 2017-07-22 at 6 27 38 pm](https://user-images.githubusercontent.com/13101565/28489697-d3d45d64-6f0b-11e7-808d-4129244ea59e.png)

as you can see it's a bit hard to spot similar words thought they're 'highlighted' due to the very transparent highlighting (i guess).

Cheers,

**Comment by whizkydee** [comment]
Awesome @mustafawm ,

Thanks. I'll check that out soon and take action in a moment. Please be patient.

**Comment by whizkydee** [comment]
Also @mustafawm ,

Which of the highlights are you talking about?

**Comment by Niichie** [comment]
Hello @whizkydee, after using the theme for the past few days it still seems like the bracket matching color is a touch too dark. It needs more contrast to be easily identifiable quickly!

**Comment by whizkydee** [comment]
Alright @Niichie,

Contributions are wide open. Feel free to contribute to the repo.
