### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by equinusocio** [whizkydee/vscode-material-palenight-theme#10]
Hi, i suggest you to change the name of this theme because is misleading with the original Material Theme Palenight. (which you started from)
https://github.com/equinusocio/vsc-material-theme

**Comment by equinusocio** [comment]
So you force me to request a takedown.

**Comment by whizkydee** [comment]
Hey! You'll have to wait a few days... Before I can decide whether to effect that.

Thanks.

**Comment by equinusocio** [comment]
@whizkydee Ok, so reopen this issue.
