### ISSUE TITLE
Sidebar list items too dark for good readability

### ISSUE THREAD

**Issue by nealoke** [whizkydee/vscode-material-palenight-theme#11]
After booting up `vscode` today I noticed that the overal text color changed from white to a light purple. This changes affects people like me who have disabilities with reading as the text is quite unclear to me now :( 

BTW: This is the best theme ever created by mankind 👍

**Comment by whizkydee** [comment]
Hi @nealoke ,

Thanks a lot for raising this.

Could you please be more specific about what text you're talking about? Also, it'd be great if you ccan provide a screenshot of the editor as there's no issue here on **Windows** and **Ubuntu**.

Personally, I've noticed that the new @code has some issues with language tokenization. The element selectors like `h1` and `input` as shown in the screenshot aren't supposed to be highlighted that way.

![bad_tokenization](https://user-images.githubusercontent.com/8625066/32800931-f2e99ad2-c97b-11e7-8f10-f037f77b24cb.png)

VS Code doesn't seem to recognize them as element selectors anymore, they should have a red-ish color wit this theme activated. This seems to be a bug and I've also tried it with other themes -- it's the same result, btw it's a `.scss` file.

I presume this has already been reported to the `vscode` team and we should get a patched version soon. If this isn't the case, I'll look into raising the issue with them. Also, note that there's nothing I can do currently about that. Even the **Default Dark Theme** has the same issue.


Happy coding!

**Comment by nealoke** [comment]
@whizkydee sorry for not adding a picture :). It is not that the text is unreadable but the contrast between the background and the font color is just to low IMO. Before the update it was I think white text color which made it very clear.

![contrast](https://user-images.githubusercontent.com/17417414/32833484-50635d00-c9ff-11e7-81ca-a310bb00c117.PNG)

**Comment by whizkydee** [comment]
Thanks @nealoke,

'Will look into that soon. Sorry for the inconvenience .

**Comment by whizkydee** [comment]
Hi @nealoke,

Sorry, I forgot to state that you could do a workaround via your `settings.json` file with;

```json
{
  "workbench.colorCustomizations": {
    "sideBar.foreground": "#ffffffcc"
  }
}
```

* `sideBar.foreground` modifies the color of the sidebar items and the items in the command palette
* `#ffffffcc` is the color that was used initially before the `v1.6.0` release

I hope you find it helpful.

**Comment by nealoke** [comment]
@whizkydee so it will not be changed by default? 😢 Thanks for the workaround!

**Comment by whizkydee** [comment]
@nealoke It will, but It'll probably still look similar to its current appearance (or not).

**Comment by nealoke** [comment]
@whizkydee I've used the workaround you gave me but the following still remains. Could it be because it is ignored in my .gitignore file?

![weird](https://user-images.githubusercontent.com/17417414/33278684-9dbae6c6-d39c-11e7-82ba-23256f975c42.PNG)

**Comment by whizkydee** [comment]
Yeah @nealoke It's because it's ignored in your `.gitignore` file. I guess that's great, or what do you think?

**Comment by aewing** [comment]
@nealoke try the following... Should make ignored resources and multiple selections a bit easier to see. Let me know if you're having trouble with anything else or would like for me to make some adjustments.

```json
  "workbench.colorCustomizations": {
    "sideBar.foreground": "#ffffffcc",
    "editor.selectionBackground": "#5C6282ff",
    "editor.selectionHighlightBackground": "#5C6282bb",
    "editor.inactiveSelectionBackground": "#5C6282cc",
    "editor.findMatchBackground": "#5C6282dd",
    "gitDecoration.ignoredResourceForeground": "#ccccccaa"
  }
```

**Comment by whizkydee** [comment]
Thanks @aewing,

I totally forgot that I hadn't responded to this.

@nealoke really sorry about that. Let me know if you find the current solution helpful.

Good luck.
