### ISSUE TITLE
Issue with displaying parenthesis in Italics version

### ISSUE THREAD

**Issue by pranit123** [whizkydee/vscode-material-palenight-theme#12]
In the scenario depicted in the screenshot, the opening parenthesis is displayed in Italics while the closing one is not.

![screen shot 2017-11-15 at 1 22 39 pm](https://user-images.githubusercontent.com/23721710/32824854-a062f79e-ca08-11e7-91ef-92e9ca88132f.png)

**Comment by whizkydee** [comment]
Thanks. 'Will look into that. What language is that by the way?

**Comment by pranit123** [comment]
Writing TypeScript in a React Project

**Comment by whizkydee** [comment]
Great @pranit123!

The file language is set to `React` ?

**Comment by pranit123** [comment]
![screen shot 2017-11-17 at 11 26 05 am](https://user-images.githubusercontent.com/23721710/32931427-2ebadbec-cb8a-11e7-9b93-0dbb3e9119dc.png)

**Comment by whizkydee** [comment]
Cool @pranit123,

I get your point now. I'll get back to you soon (hopefully).

**Comment by whizkydee** [comment]
Closing this now @pranit123. Hopefully, this issue is fixed already.

Please notify if otherwise.

Thanks.
