### ISSUE TITLE
What font are you using in the screenshot?

### ISSUE THREAD

**Issue by sdctm** [whizkydee/vscode-material-palenight-theme#14]
Not really an issue; but I'm intrigued what font you're using for the screenshot...

**Comment by whizkydee** [comment]
Hey @sdctm,

It is stated in the [README](https://github.com/whizkydee/vscode-material-palenight-theme/blob/master/README.md).

Thanks.

**Comment by boringwong** [comment]
I have Operator Mono, but it doesn't look like the font in the screenshot.

**Comment by whizkydee** [comment]
Oh, yeah. The screenshot changed since then. The new font is [FiraCode](https://github.com/tonsky/FiraCode), hope that helps.
