### ISSUE TITLE
sidebar is dark!

### ISSUE THREAD

**Issue by AcarMeel** [whizkydee/vscode-material-palenight-theme#16]
I installed this theme twice on two different PCs. The first time, it blended the sidebar with a nice purple color, but in the second one the sidebar is just dark, not purple!. I'm using the same versions of OS, VSC and the same version of the plugin. IDK what happened, I like this theme cause at first it was all purple and nice

**Comment by whizkydee** [comment]
Hi @AcarMeel,

Thanks for reporting this. Could you please attach a screenshot of the editor showing the issue for clarity and information.

Thanks.

**Comment by whizkydee** [comment]
@AcarMeel? Please indicate if this issue is still valid.

**Comment by whizkydee** [comment]
Closing this, @AcarMeel since there's no response.
