### ISSUE TITLE
All variants display comments in italic

### ISSUE THREAD

**Issue by nealoke** [whizkydee/vscode-material-palenight-theme#17]
Hi, I just updated the plugin and now all variants of the theme display the comments in italic which is something I do not want :(

![image](https://user-images.githubusercontent.com/17417414/34640654-100cca2c-f2f7-11e7-8609-0673552161b0.png)

**Comment by whizkydee** [comment]
Hello @nealoke,

Setting comments to italic is somewhat a standard for editor themes and totally escaped my mind while building this theme. The moment I noticed it, I added it to the theme.

Sorry for the inconvenience. Your `settings.json` file is your friend 😉 .

Thanks.

**Comment by nealoke** [comment]
@whizkydee ok :)
