### ISSUE TITLE
Handlebars templates are hard to read

### ISSUE THREAD

**Issue by offirgolan** [whizkydee/vscode-material-palenight-theme#18]
Hi there,

Absolutely love this theme! The only issue I have is that it's incredibly hard to read handlebar templates since its almost all purple. Would it be possible to add some more contrast?

<img width="590" alt="screen shot 2018-02-01 at 11 58 54 am" src="https://user-images.githubusercontent.com/575938/35700347-9c8cf9a4-0747-11e8-9f81-dc60608bae5a.png">
<img width="425" alt="screen shot 2018-02-01 at 11 59 09 am" src="https://user-images.githubusercontent.com/575938/35700348-9cbd6af8-0747-11e8-8ee3-99072c9fe85e.png">

Here is a good example (using the Atom Material Theme):
<img width="583" alt="screen shot 2018-02-01 at 12 03 08 pm" src="https://user-images.githubusercontent.com/575938/35700472-f2c6b382-0747-11e8-8de7-3647609302fc.png">

**Comment by whizkydee** [comment]
Thanks @offirgolan,

'Will look into that soon.
