### ISSUE TITLE
Selection Highlight contrast is not optimal

### ISSUE THREAD

**Issue by pichfl** [whizkydee/vscode-material-palenight-theme#2]
First off: I love this theme.

The current highlight color has very low contrast against the background which makes it close to invisible in many situations. I replaced the colors in my local config as follows, but I'm not happy yet with the colors and also I'm missing the selector for coloring selections created by super + d (select next occurence of selected word)

```json
{
    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#4C5290",
        "editor.selectionHighlightBackground": "#383D63",
        "editor.findMatchBackground": "#4F855A",
        "editor.findMatchHighlightBackground": "#4F857E"
    }
}
```

Maybe you have a better idea on how to make the highlight and selection states a little more prominent?

**Comment by whizkydee** [comment]
Thanks @pichfl ,

Could you please provide a screenshot describing this issue. Or better, a video or GIF. I think I do not understand you accurately.

Cheers!

**Comment by bajras** [comment]
Very nice theme, was this addressed. Below is the attached screenshot. When I highlight a text or double click a text to highlight, the highlighted color is very light and hard to see. Is there a way I can update that locally? Thanks.

<img width="186" alt="screen shot 2017-10-26 at 9 39 19 pm" src="https://user-images.githubusercontent.com/3359989/32085747-93278fda-ba96-11e7-8007-553c6fa6e165.png">

**Comment by whizkydee** [comment]
Hi @bajras ,

Thanks for raising this issue again.

Could you please specify the version of the theme you're using? The selection highlight colors were updated two days ago in `v1.5.4`. If it doesn't still look great, I'll consider adjusting it again.

You could temporarily also change the colors with `"workbench.colorCustomizations"` in your `settings.json` file. Say;

``` json
"workbench.colorCustomizations": {
  "editor.selectionBackground": "YOUR_HEX_HERE",
  "editor.selectionHighlightBackground": "YOUR_HEX_HERE"
}
```

It would be appreciated if you find a good HEX code and share with me.

Cheers!

**Comment by bajras** [comment]
1.5.4, Like below im selecting the word apply only but I cant really see the highlight just on the word.

<img width="186" alt="screen shot 2017-10-26 at 9 39 19 pm" src="https://user-images.githubusercontent.com/3359989/32108146-5ce8ec74-baf6-11e7-98f1-bc8e3c370349.png">

**Comment by pichfl** [comment]
I think in addition to the `editor.selectionBackground` there is some other mechanic overwriting this color. It may be that VSCode detects the same property name somewhere else in the document and uses another keyword because of that. I'm not sure which that would be.

I think the whole highlight color situation in Code is really hard to get right :/

**Comment by bajras** [comment]
Ya its strange, when im selecting `const` it works fine but not when I select `getData' or event the variable names. 

![screen shot 2017-10-30 at 10 11 14 am](https://user-images.githubusercontent.com/3359989/32178444-b3865038-bd5a-11e7-8650-c2079c918027.png)
![screen shot 2017-10-30 at 10 11 35 am](https://user-images.githubusercontent.com/3359989/32178445-b554c9f8-bd5a-11e7-881d-8bcf9c965341.png)

**Comment by whizkydee** [comment]
Hi guys,

**Quick one**: I absolutely appreciate the fact that you guys are really concerned about this issue --Thanks a bunch 👍 !

Meanwhile, the irregular **selection highlight** color definitely seems to be an issue with `vscode`. I'll look into it deeply and report to `vscode` if neccessary.

Also, @bajras, were you able to reproduce this in `vscode/stable`? In case you also have the **Custom CSS and JS Loader** installed, it might be that some styles are being overwritten -- You might also want to look in to that too.

About the general **selection highlight** color of the theme; I'll look into make it clearer 🎉.

Thanks!

**Comment by bajras** [comment]
I havent tried on the stable version of if yet, but thats a good idea. I have created an issue on VScode as well. Thanks. 
https://github.com/Microsoft/vscode/issues/37047

**Comment by pichfl** [comment]
I think 

> Make sure all the selection colors use transparency.

from [the comments](https://github.com/Microsoft/vscode/issues/37047#issuecomment-340469410) of that ticket might be an interesting bit of information. The colors I suggested in my original issue are not transparent. Maybe this makes a difference.

**Comment by whizkydee** [comment]
Oh... Wow!

Thanks @pichfl ,

It's something I really missed out. Thanks for pointing it out to me.. I'll try that in a bit.

**Comment by bajras** [comment]
Please let me know when you do. Thanks.

**Comment by bajras** [comment]
`"workbench.colorCustomizations": {
    "editor.selectionBackground": "#9510ee80",
    "editor.wordHighlightBackground": "#9510ee80",
    "editor.wordHighlightStrongBackground":"#9510ee50"
  }`

Doing that fixed it for me after using transparent, I would highly recommend updating the selections to have more focus. Thanks

**Comment by Gujie-Novade** [comment]
I've found another extension which will add borders to the selection. This may help you guys too:
https://marketplace.visualstudio.com/items?itemName=iceliu.highlight-icemode
Here's a screenshot:
![image](https://user-images.githubusercontent.com/14208739/34372483-b1612488-eb07-11e7-9d9b-ead1a4e446e8.png)
