### ISSUE TITLE
highlight is not obvious

### ISSUE THREAD

**Issue by jasonxia23** [whizkydee/vscode-material-palenight-theme#20]
![image](https://user-images.githubusercontent.com/15098719/36013120-5cfa3ba6-0d9d-11e8-8a03-6be475be03ba.png)

Especially in `.vue` files.
![image](https://user-images.githubusercontent.com/15098719/36013222-057901a4-0d9e-11e8-85b2-336134dceaf3.png)

**Comment by whizkydee** [comment]
Hello @jasonxia23,

Hopefully, this issue has been resolved already, kindly hint if otherwise. However, you can hack around this with the `"workbench.colorCustomizations"` object in your `settings.json` file.

You'd do something like...

``` json
"workbench.colorCustomizations": {
  "editor.selectionBackground": "YOUR_HEX_HERE",
  "editor.selectionHighlightBackground": "YOUR_HEX_HERE"
}
```

You can check out #2 too. Thanks.
