### ISSUE TITLE
Colors Differ Between Machines - Palenight Operator

### ISSUE THREAD

**Issue by Jaballadares** [whizkydee/vscode-material-palenight-theme#23]
Hi there, first off thanks for the beautiful theme! Forgive me if I'm submitting this incorrectly.

Are there any known reasons for why two pieces of identical code would have different syntax highlighting colors applied to them? I noticed it when my coworker sent a screenshot of her code and I compared it to the one running on my machine. 

I've disabled other plugins, and still no luck. I guess I am just a bit jealous of how great her code looks with the additional highlighting. 

**Theme**: Palenight Operator
**Font**: Operator Mono
**Language** : JavaScript

**My VS Code:**
<img width="578" alt="my-palenight" src="https://user-images.githubusercontent.com/4951251/39892207-b21cd226-5454-11e8-81d2-fd0ab2bfa059.png">

**Coworker's VS Code:**
![coworkers-palenight](https://user-images.githubusercontent.com/4951251/39892214-bb8a8920-5454-11e8-9461-4db676410ee7.png)

**Comment by whizkydee** [comment]
Hello @Jaballadares,

Thanks for reaching out. I suggest you take note of the language your co-worker's code is set to. This is definitely strange. Check that out, and let me know your findings.

Cheers.
