### ISSUE TITLE
Commit message validation is unable to be read using Palenight Theme

### ISSUE THREAD

**Issue by ndcunningham** [whizkydee/vscode-material-palenight-theme#24]
I love this theme and just wanted to point out an issue which i have found and unsure if this is intended. It occurs when I use the Palenight Theme.

From the image below you can see the problem.
![screen shot 2018-05-17 at 9 36 36 am](https://user-images.githubusercontent.com/338948/40181019-20a8fe2a-59b6-11e8-8f15-bdc4d981f73c.png)

I fix this problem you have to add a custom setting to change the `inputValidation.warningBackground`
property of the Palenight Theme we set it to `#41471b`

The result is below:
![screen shot 2018-05-17 at 9 40 41 am](https://user-images.githubusercontent.com/338948/40181174-76761806-59b6-11e8-93ed-b0f458066d71.png)

Thanks

**Comment by whizkydee** [comment]
Oh, wow! Thanks. I'll check it out asap.
