### ISSUE TITLE
Theme looks different (too much purple) on Ubuntu 

### ISSUE THREAD

**Issue by ketozhang** [whizkydee/vscode-material-palenight-theme#25]
The theme looks a bit too purple than the screenshot in README. Is this what its suppose to look like (see screenshot below)?

![image](https://user-images.githubusercontent.com/13506487/40285863-cd502f94-5c55-11e8-97c9-8dd5e5aa7191.png)

I love this theme because it's like One Dark but with a hint of purple but this is too much.

Using VSCode for Ubuntu (don't think this matters too much)

**Comment by ketozhang** [comment]
Spooky, the screenshot that I took looks perfect but its different than on my VSCode. I'm not sure how to show you what's wrong then.

**Comment by Jaballadares** [comment]
@ketozhang this happens to me too! Most of the time, this is has more to do with monitor/screen you are using. I have my laptop and work _monitor_ side-by-side most days, and there's a surprisingly big difference in how different the colors look.

**Comment by whizkydee** [comment]
@ketozhang thanks for reaching out! My bad, I'm just seeing this. Also, thanks @Jaballadares for the answer.

I think this is what you're experiencing, @ketozhang. Could you consider that and let me know what you find?

Cheers!
