### ISSUE TITLE
editor.findMatchHighlightBackground is not eye-catching

### ISSUE THREAD

**Issue by lcysgsg** [whizkydee/vscode-material-palenight-theme#26]
![default](https://user-images.githubusercontent.com/19550000/40584867-680d9ea6-61db-11e8-907f-726c52ffdbc7.png)

Windows 10 , VsCode 1.23.1
I even can not see that.. 
Could you tell me why design this `"editor.findMatchHighlightBackground": "#2E3248",`
Do you will change the color more eye-catching? 

good theme, thank you

**Comment by whizkydee** [comment]
This should be fixed already. Closing now. If otherwise, I'll re-open. Thanks.
