### ISSUE TITLE
Distinguish component color from html element color

### ISSUE THREAD

**Issue by liamwang** [whizkydee/vscode-material-palenight-theme#27]
Here is Material Palenight Theme:

![image](https://user-images.githubusercontent.com/5000396/43118217-7f4d12f0-8f43-11e8-92a8-a4d525cd84e6.png)

Expect to make the color difference between component and html element in jsx syntax.

Like the One Dark Pro Theme does:

![image](https://user-images.githubusercontent.com/5000396/43118272-c28647ee-8f43-11e8-9a2e-a92de458e87a.png)

**Comment by whizkydee** [comment]
Hi! I'm aware of that, and I'd like to retain it. Not all themes differentiate the two tokens too. It's unique to One Dark Pro and some other themes.

If you're not so comfortable with it, you can add a different colour to `entity.name.tag support.class.component`.

Thanks.
