### ISSUE TITLE
Template string highlighting

### ISSUE THREAD

**Issue by getsetbro** [whizkydee/vscode-material-palenight-theme#3]
Can you add template string highlighting?
![image](https://user-images.githubusercontent.com/442793/29741934-416ea962-8a44-11e7-9be9-5e87b3cdb45a.png)

**Comment by whizkydee** [comment]
Oops... :(,

Thanks @getsetbro, I didn't actually notice that. It works for in-line template strings but I didn't take note of the the block form.
Could you please specify if you're using any **JS framework** in this code, or it's just **Vanilla**.

I look into that and push the patch in the next version.

Cheers! :+1:

**Comment by getsetbro** [comment]
I am using Vue js.

Cheers

**Comment by whizkydee** [comment]
Great... The language set in VSCode for that file is JavaScript? Or you installed an extension for Vue.

**Comment by getsetbro** [comment]
It is just a .js file.
I have a small sample app of it here: https://github.com/getsetbro/simple_vue_app
It is running here: http://getsetbro.com/simple_vue_app/

**Comment by whizkydee** [comment]
Alright @getsetbro ,

I'll check it out soon and fix it.

Thanks.

**Comment by whizkydee** [comment]
Hi @getsetbro,

Unfortunately, **HTML** and other **markup** languages currently can't be highlighted by **VSCode** in **JavaScript** template strings. That whole code is grouped and identified as a template string. It's not tokenized as **markup** as to separate each tag and atrribute.

You can try it on other themes too. It's the same. 😉 

**P.S**: You should star this repo 🙏 

Thanks 👍
