### ISSUE TITLE
Theme styles aren't applying for markdown preview code blocks

### ISSUE THREAD

**Issue by dumindu** [whizkydee/vscode-material-palenight-theme#31]
Before:
![before](https://i.redd.it/bu4uqjq42ry01.png)

Now: 
![now](https://i.imgur.com/rwpKJUU.png)
Now applying vscode default theme styles.

**Comment by whizkydee** [comment]
@dumindu this issue is most likely related to VSCode or the plugin as I didn't intentionally design for it.

In fact, the syntax highlighting in the first screenshot is not the one of this theme. Please double check and let me know the outcome.

Closing now. Thanks!
