### ISSUE TITLE
Contribute to this Project

### ISSUE THREAD

**Issue by whizkydee** [whizkydee/vscode-material-palenight-theme#5]
## Help Out!

Please help contribute to this project. Here are a few things I would love to implement :wink:. Get to understand the whole thing by reading the [contributing guide](https://github.com/whizkydee/vscode-material-palenight-theme/blob/master/CONTRIBUTING.md).

- [ ] Automate copying every change in a JSON file into the **variants**. Say, you edit *palenight.json*, your changes should get duplicated in *palenight-italic.json* and *palenight-operator.json*.
- [ ] Create a functionality that'll group the code for each language in separate files. Say, *javascript.json*, *css.json* and would automtically be merged into one file on build.
- [ ] Create a variant for users with eye issues.
- [ ] Help update the [Atom version](https://github.com/whizkydee/atom-material-palenight-syntax).
- [ ] Support this project. [Get me coffee](https://me.wallet.ng/mrolaolu) :smirk: :pray:!

Thanks for showing interest and helping out :ok_hand:!

If you get stuck somewhere, reach out to me on [Twitter](https://twitter.com/mrolaolu) :smile:.

**Comment by shalvah** [comment]
@whizkydee I think it would bring better visibility if you broke up each of the mentioned issues into separate GitHub issues, and get them on the hacktoberfest site

**Comment by whizkydee** [comment]
Thanks @shalvah ,

I'll consider that.

**Comment by nealoke** [comment]
@whizkydee I could help out here, I'm not sure when this will be but I'll put it on my todo list. I'll tackle the first task for copying into the variants 👍

**Comment by whizkydee** [comment]
Hey @nealoke !

Thanks again for showing interest in this. You're very much welcomed on this. 'Would love to see you get started soon.

Cheers!
