### ISSUE TITLE
Cursor blinking is barely visible in HTML file

### ISSUE THREAD

**Issue by lordgreg** [whizkydee/vscode-material-palenight-theme#7]
Hi. I love the theme. It is awesome!

There is just one thing, which really bothers my development. If in HTML file and creating new element with typing "p" and pressing enter or tab, it will create `<p></p>` and put the cursor in the middle. The blinking cursor is barely visible.

![image](https://user-images.githubusercontent.com/480546/31490916-d96d8d3e-af45-11e7-9c45-0f3bed33fbee.png)

Can this get fixed somehow?

**Comment by whizkydee** [comment]
Hi @lordgreg ,
First off, Thanks for using this theme. I'm glad you love it!

This doesn't look like an issue associated with the theme. The cursor color is fine, but the default bracket matching behaviour in VS Code is weird. If you don't mind a few tweaks though, here;

Add the snippets you find helpful to your `settings.json` file;

1. You might want to disable the borders around the `<` and `>` with:
``` json
"editor.matchBrackets": false
```
_Or..._

2. You can change the cursor color with:
``` json
"editor.tokenColorCustomizations": {
  "editorCursor.foreground": "YOUR_HEX_HERE"
}
```

I hope this solves your problem.

Cheers 🎉!
