### ISSUE TITLE
It is weird that curly braces are italic in jsx.

### ISSUE THREAD

**Issue by SidKwok** [whizkydee/vscode-material-palenight-theme#8]
<img width="149" alt="2017-10-13 14 08 30" src="https://user-images.githubusercontent.com/13268747/31532468-13216bdc-afb3-11e7-86a9-a9fe3da0f1ee.png">
<img width="293" alt="2017-10-13 14 08 36" src="https://user-images.githubusercontent.com/13268747/31532472-194f1ae0-afb3-11e7-9d40-16189bc06c36.png">

It happens only in jsx. I think it would be better to keep curly braces `normal`.

palenight for Opearator Mono

**Comment by whizkydee** [comment]
This looks great @SidKwok . I'll look into it in a few minutes.
